# Generated by Django 5.2.14 on 2026-05-12 00:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Casa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manzana', models.CharField(max_length=50)),
                ('lote', models.CharField(max_length=50)),
                ('calle', models.CharField(max_length=100)),
                ('numero_exterior', models.CharField(max_length=10)),
            ],
            options={
                'verbose_name': 'Casa',
                'verbose_name_plural': 'Casas',
            },
        ),
        migrations.CreateModel(
            name='Residente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('es_titular', models.BooleanField(default=True)),
                ('casa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='residentes', to='residencial.casa')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil_residente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Residente',
                'verbose_name_plural': 'Residentes',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fecha_pago', models.DateField(auto_now_add=True)),
                ('mes_correspondiente', models.DateField()),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('PAGADO', 'Pagado'), ('ATRASADO', 'Atrasado')], default='PENDIENTE', max_length=20)),
                ('comprobante', models.FileField(blank=True, null=True, upload_to='comprobantes/')),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pagos', to='residencial.residente')),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
            },
        ),
    ]
