# Generated by Django 5.2.14 on 2026-05-12 00:01

import django.db.models.deletion
import pyotp
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('residencial', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_completo', models.CharField(max_length=200)),
                ('fecha_visita', models.DateField()),
                ('secreto_totp', models.CharField(default=pyotp.random_base32, max_length=32)),
                ('es_valida', models.BooleanField(default=True)),
                ('residente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitaciones', to='residencial.residente')),
            ],
            options={
                'verbose_name': 'Invitado',
                'verbose_name_plural': 'Invitados',
            },
        ),
        migrations.CreateModel(
            name='Acceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('tipo', models.CharField(choices=[('ENTRADA', 'Entrada'), ('SALIDA', 'Salida')], max_length=10)),
                ('observaciones', models.TextField(blank=True)),
                ('guardia', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='accesos_registrados', to=settings.AUTH_USER_MODEL)),
                ('residente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='residencial.residente')),
                ('invitado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accesos.invitado')),
            ],
            options={
                'verbose_name': 'Acceso',
                'verbose_name_plural': 'Accesos',
            },
        ),
    ]
