# Generated by Django 6.0.2 on 2026-02-05 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('nombre', models.CharField(max_length=80)),
                ('apaterno', models.CharField(blank=True, max_length=80, null=True, verbose_name='Apellido Paterno')),
                ('amaterno', models.CharField(blank=True, max_length=80, null=True)),
                ('genero', models.CharField(choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Otro', 'Otro')], default='Otro', max_length=8)),
                ('email', models.EmailField(max_length=254)),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField(default=0)),
                ('altura', models.DecimalField(decimal_places=2, max_digits=3)),
                ('red_social', models.URLField()),
                ('imagen_perfil', models.ImageField(upload_to='')),
                ('activo', models.BooleanField(default=True)),
                ('fecha_modifica', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
