# Generated by Django 6.0.2 on 2026-02-10 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='catalogo_estados_municipios',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clave_entidad', models.IntegerField()),
                ('nombre_entidad', models.CharField(max_length=120)),
                ('clave_municipio', models.IntegerField()),
                ('nombre_municipio', models.CharField(max_length=120)),
                ('poblacion_total', models.BigIntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='amaterno',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Apellido Materno'),
        ),
        migrations.AlterField(
            model_name='personamodel',
            name='nombre',
            field=models.CharField(max_length=80, verbose_name='Nombre(s)'),
        ),
    ]
