# Generated by Django 6.0.2 on 2026-02-12 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0002_catalogo_estados_municipios_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.TextField()),
                ('cp', models.IntegerField(verbose_name='Código Postal')),
                ('estado_municipio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.catalogo_estados_municipios')),
            ],
        ),
    ]
