# Generated by Django 6.0.2 on 2026-02-12 14:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MiApp', '0003_datosgenerales'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonaDatosGenerales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_registro', models.DateTimeField(auto_created=True, auto_now_add=True)),
                ('datos_generales', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.datosgenerales')),
                ('persona', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MiApp.personamodel')),
            ],
        ),
    ]
