# Generated by Django 6.0.3 on 2026-03-26 14:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricula', models.CharField(max_length=8)),
                ('nombre', models.CharField(max_length=80)),
                ('apaterno', models.CharField(blank=True, max_length=80, null=True)),
                ('amaterno', models.CharField(blank=True, max_length=80, null=True)),
                ('genero', models.CharField(choices=[('MUJER', 'MUJER'), ('HOMBRE', 'HOMBRE'), ('OTRO', 'OTRO')], default='OTRO', max_length=8)),
                ('edad', models.IntegerField(default=0)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_clase', models.CharField(max_length=120)),
                ('tipo', models.CharField(choices=[('PRESENCIAL', 'PRESENCIAL'), ('VIRTUAL', 'VIRTUAL')], default='PRESENCIAL', max_length=20)),
                ('fecha_asistencia', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asiste', models.BooleanField(default=True)),
                ('detalle', models.CharField(blank=True, help_text='Justificación de no asistencia', max_length=150, null=True)),
                ('alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.alumno')),
                ('asistencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.asistencia')),
            ],
        ),
    ]
